### ISSUE TITLE
Create widget that updates with the featured image of most recent post from MishMoments

### ISSUE THREAD

**Issue by wrightcj03** [a8cteam51/mish-shedlock#4]
The widget should be placed after the blog archive and before the current Mish Moments widget.

## Requirements  
- Display featured image of most recent post on MishMoments.com
- Width will be 300px, height will be variable (to accommodate both portrait and landscape photo orientations)
- Automatically update when there's a new post on MishMoments

Here's a few ideas for how this could be done: 
- [Syndication plugin](https://vip.wordpress.com/plugins/syndication/): VIP approved, would require Mish to select which site he'd like to push to but maybe we could auto check this box on in the post editor on Mish Moments.
- [Alter the RSS](https://vip.wordpress.com/documentation/vip-development-tips-tricks/altering-feeds/) feed on MishMoments to include the featured image Featured image in RSS (there's a [plugin](https://wordpress.org/plugins/featured-image-in-rss-feed/) to do this that's not VIP approved)

**Comment by michiecat** [comment]
I've got a custom feed created that just shows the featured image, but I'm having trouble getting the image to actually appear in the built-in RSS widget. I'm going to need a little more time to work that out, but we're getting closer! 

The new custom feed is at: http://mishmoments.com/?feed=featured-image-feed

**Comment by danielwrobert** [comment]
I was having a little bit of trouble getting the images to display in the content or the description blocks. I'm wondering if they were getting stripped out by the widget for security reasons.

Regardless, I decided to take a little bit of a different approach. I used the WPCOM API to pull the latest 5 posts via an AJAX request and rendered to a text widget via JavaScript.
